### ISSUE TITLE
Filter author - exclude one (or list) of author(s)

### ISSUE THREAD

**Issue by karol-bujacek** [artreven/pp_api#10]
Hello Artem,

Is it possible to use this function to exclude an author from the result? I.e., 'graphsearch, give me articles with any author, except XYZ'. Can something like 'not in [author1, author2]' be put as a value for filter?

https://github.com/artreven/pp_api/blob/761de650b83adeb744dd19816e7f75c8daca1ef2/pp_api/gs_calls.py#L197

**Comment by artreven** [comment]
Unfortunately, exactly what you ask is not supported by GraphSearch, i.e. it is neither possible to issue an HTTP request to exclude author nor to get the full list of authors.
However, if you already somehow know the list of all authors then you can prepare several author filters and send several search requests to get the articles for other authors. Namely, if you have authors 1 to 10 and you would like to do `not in [author1, author2]` you can prepare filter for authors 3 to 10.
