### ISSUE TITLE
Faceted search

### ISSUE THREAD

**Issue by karol-bujacek** [artreven/pp_api#11]
Hello Artem,

I need to implement faceted search feature at the platform and right now I’m trying to display something very simmilar to the left sidebar at page https://profit.poolparty.biz/GraphSearch/ (I better avoided to include the screenshot, I don’t know if I can publish that images publicly here). I mean the list of some terms with numbers representing the number of articles for appropriate term.

(Note: maybe I’m lost in the terminology, I may use words like ‘facets’, ‘terms’ etc. with different meaning – I hope it will be possible to guess what I’m talking about :-) )

At the moment, I’m using `GraphSearch > search` method which gives me results/response.

If I try to show JSON of the response, there are facetList arrays for each result, like this:
```
# here in the json structure
{
  'results': [
    {
      'facetList': [{ .... }]
    }, ...
}
```
But it seems to me like different terms for each article in the result and not what I’m searching for.

Can you help me or give an example, please, what methods should I use when I want to achieve this:

---

- Given I’m at the search page
And I don’t specify any search term (“fulltext input”)
- When I press the search button
- Then I will see all articles in the list
And I will see some terms with numbers in the sidebar

---

- Given I’m at the search page
And I write any string into “fulltext input”
And I select any term from the sidebar
- When I press the search button
- Then I will see smaller group of articles in the list
And I will see different terms with smaller numbers in the sidebar

---

Also, if method `GraphSearch > filter_cpt`should be used for this, can you show me an example input for one value and for multiple values? (e.g. selecting ‘enterpreneurship’, or selecting ‘inflation’ + ‘enterpreneurship’).

Thanks you a lot.

**Comment by artreven** [comment]
Actually what you get in the `results > facetList` is exactly what you need. The list contains different terms (we call them concepts because they come from a thesaurus and every instance in a SKOS thesaurus is usually called a concept) that are found in the current document. The frequencies in `facetList` are for this document, so these are **not** the frequencies you want. What you would need to do is to go through all the results and aggregate for each concept in how many documents it is found.
When the user clicks on a concept, you would prepare `filter_cpt` for this concept. The value to be used in the `filter_cpt` parameter can be constructed as `prefix + facetList[i]['value'].split('_')[-1]` and the prefix is fixe (`http://profit.poolparty.biz/profit_thesaurus/` in our case).

There are also special concepts that correspond to concept schemes of a thesaurus. In our case it is `EuroVoc 4.3` and `STW`. They have a longer list of facets that includes all concepts from these concepts schemes and there correct URIs (in `label` key). The `count`s there mean nothing though.

**Comment by karol-bujacek** [comment]
Thank you, I’ll try it.

**Comment by karol-bujacek** [comment]
Creating concept filter:
```
            cpt_uri = "http://profit.poolparty.biz/profit_thesaurus/{}".format(concept_id)
            gs_filter = self.graph_search.filter_cpt(cpt_uri)
```

(concept_id is an integer)

And response:

```
{'method': 'POST', '_body_position': None, 'body': b'{"documentFacets": ["all"], "count": 30, "searchFilters": [{"optional": false, "value": "wall street", "field": "full_text_search"}, {"value": "http://profit.poolparty.biz/profit_thesaurus/5823", "field": "dyn_uri_all_concepts"}], "searchSpaceId": "067a55d6-*****************-08ea6873bb88", "locale": "en"}', 'headers': {'Content-Type': 'application/json', 'Connection': 'keep-alive', 'Authorization': 'Basic bWF******************ZpdA==', 'Accept': '*/*', 'Accept-Encoding': 'gzip, deflate', 'Content-Length': '303', 'User-Agent': 'python-requests/2.13.0'}, '_cookies': <RequestsCookieJar[]>, 'hooks': {'response': []}, 'url': 'https://profit.poolparty.biz/GraphSearch/api/search'}



<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>PoolParty - Internal Error</title>
    <link rel="SHORTCUT ICON" href="/favicon.ico">
    <link rel="stylesheet" href="/GraphSearch/styles/css/admin/error-pages.css;jsessionid=07C87AC4072128914A717C5195B55F4A" type="text/css"/>
</head>
<body>
<div class="error-container">
    <div style="text-align:center">
        <img src="/GraphSearch/images/pp_logo.jpg;jsessionid=07C87AC4072128914A717C5195B55F4A" border="0" alt="PoolParty"><br>
        <h2>Internal Error</h2>
        <p>No value present</p>
    </div>
</div>
</body>
</html>
```

What I’m doing bad?

**Comment by artreven** [comment]
This is very strange, because for many commits already the `filter_<something>` calls do not do any requests and just prepare filters. Please, check you are using the latest version

**Comment by karol-bujacek** [comment]
No, that's not strange – I’m applying the filter prepared with filter_cpt (i.e. searching using that filter).

**Comment by artreven** [comment]
Ok, could you then post the call to preparing filter and the call to `gs.search`

**Comment by karol-bujacek** [comment]
Please take a look at this code. I’ve prepared three tests as an example. Third one, `test_search_with_filter_cpt_response_OK` is failing.

https://github.com/Project-PROFIT/pp_api/commit/9145a69ed6a64559349976edd4ca0c0f5405dfbf

```
PP_SERVER=https://p***t.p***y.b**
GRAPHSEARCH_USER=m****n
GRAPHSEARCH_PASS=m****it
GRAPHSEARCH_SEARCH_SPACE_ID='067a55d****bb88'
```

**Comment by artreven** [comment]
Thanks @karol-bujacek !
In the latest commit (322e300173016d0ced9372c31091f1d9e2073bc3) the tests are all passing. Please, check if this tackles the issue and close if no further problems pop up.
